### ISSUE TITLE
Loop Function

### ISSUE THREAD

**Issue by RayDog1995** [kalebbroo/plex_music_bot#10]
Just a reminder to add loop ability when you have time.

**Comment by kalebbroo** [comment]
Can you be more specific on what you want it to do? Just loop the queue? Right now When a song plays it deletes from the queue so I would have to code something specific for that.

**Comment by RayDog1995** [comment]
The way ive like it to work is when /loop is activated it will keep repeating the current song. If possible, since your using the fancy / shtuff could you make a button next to pause next etc for loop, and maybe a step further is a cyclable loop where if you press it once  it loops infinitely, the next click is single loop and another is two loops? Idk if this is related but being able to go back 1 or two songs. Thought of it since looping might involve caching anyway, or I could be dum dum.

**Comment by jacobmix** [comment]
A lot of music players have buttons like that. Loop file, loop playlist, loop x times.
Could probably add something like that. Click a loop button to keep looping song till it's clicked again, and continues the queue.
Or use a command if you wanna loop the current song like 4 times. Maybe add a true/false to playlists/queues if you wanna loop them just like shuffle is. A command to disable current queue loop would be good too.
I also made a suggestion for a default playlist https://github.com/kalebbroo/plex_music_bot/issues/13 that would shuffle on loop if no playlist, ect is queued up.

**Comment by kalebbroo** [comment]
This has been added in the rewrite of the bot.
