### ISSUE TITLE
Unable to setup in Docker

### ISSUE THREAD

**Issue by ghostyjag** [kalebbroo/plex_music_bot#12]
I seem to be getting an error when attempting to copy the requirements.txt and app folder into the container upon building the container. I believe this is an issue with my WORKDIR?

COPY failed: file not found in build context or excluded by .dockerignore: stat requirements.txt: file does not exist

**Comment by kalebbroo** [comment]
Are you using the master branch or the latest release build? Please try the v0.8 release.

**Comment by ghostyjag** [comment]
Thank you for the reply. 
I just attempted with the v0.8 release and receive the same error at the point of copying requirements.txt into the container.
