### ISSUE TITLE
Unknown... It wont respond to commands.

### ISSUE THREAD

**Issue by Wolferator1504** [kalebbroo/plex_music_bot#14]
[5-20 log 1.txt](https://github.com/kalebbroo/plex_music_bot/files/15373884/5-20.log.1.txt)

**Comment by Wolferator1504** [comment]
[Lavalink 5-20 log 1.txt](https://github.com/kalebbroo/plex_music_bot/files/15373971/Lavalink.5-20.log.1.txt)
[5-20 log 2.txt](https://github.com/kalebbroo/plex_music_bot/files/15373910/5-20.log.2.txt)
![Capture](https://github.com/kalebbroo/plex_music_bot/assets/35203545/261d4c37-8818-49a5-9e74-42750c258ff7)

idk what changed but it did play the track just without a embed.

**Comment by kalebbroo** [comment]
The command you want is the /search command. 

Currently/play is just a test command I made to play  YouTube. I should rename it until I get a proper implementation.

**Comment by kalebbroo** [comment]
From your lavalink logs:
`: YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions.` 

Is that your full bot log or only the part with the error? I dont see any of the startup stuff in console.

**Comment by kalebbroo** [comment]
If adding your username and pass does not fix the issue you can reopen this issue.
