### ISSUE TITLE
Request: Have it play playlists in the order they are.

### ISSUE THREAD

**Issue by Wolferator1504** [kalebbroo/plex_music_bot#4]
Have it play playlist in the order they are instead randomly. Maybe also add a argument to randomize the playlist like; '-r' at the end.
User: !playlist
Bot: Available Playlists
1. Sample 
2. Sample

User: 1 -r

**Comment by kalebbroo** [comment]
Just released the next beta update and i included this feature.

The commands are now slash commands. This is how it will work:
<> = required field 
[ ] = optional field

/playlist <shuffle: True/False> [playlist_name]

![playlist_true](https://github.com/kalebbroo/plex_music_bot/assets/10682641/2a138f86-71df-4159-8833-376ab6af70ab)
