### ISSUE TITLE
Youtube URL playback is broken

### ISSUE THREAD

**Issue by Wolferator1504** [kalebbroo/plex_music_bot#5]
Bot gets stuck "thinking" when trying to use Youtube URL's. There is a error code in the Console for the bot as well.

**Comment by kalebbroo** [comment]
Fixed. Expect a rework of all youtube related functions soon. Playlists are still a pain in the ass.
https://github.com/kalebbroo/plex_music_bot/commit/547a41c48fbb1a9f16bea223545a9b0b692eb76f
