### ISSUE TITLE
Auto-disconnect Timer

### ISSUE THREAD

**Issue by BluesKabooze** [kalebbroo/plex_music_bot#6]
The disconnect timer is rather short which causes frequent disconnect and reconnects when our users use the bot. We're a small server so we frequently check to see who joined only to find the same list of users, which in turn makes us sad.

If the disconnect timer could be raised to 10 or 15 minutes that would be great. Thank you for all your efforts thus far!

**Comment by kalebbroo** [comment]
Feature has been added.
