### ISSUE TITLE
Activity Suggestion.

### ISSUE THREAD

**Issue by SnkyFrsh** [kalebbroo/plex_music_bot#8]
![image](https://github.com/kalebbroo/plex_music_bot/assets/69320782/8c450704-720c-49fc-9a40-2c7968bff4f3)

**Comment by kalebbroo** [comment]
![playing](https://github.com/kalebbroo/plex_music_bot/assets/10682641/22d1cce9-ecdc-4c30-8025-6aa3fd44ee33)
This feature has been added. 

I am looking into adding the album artwork but it does not seem to be natively supported. unless im missing something. It looks like this can be done with a separate script but that is not something I would want.

**Comment by kalebbroo** [comment]
This is added but I dont see a good way to have this active with multiple servers. so I think im going to make a bool in the config to it can be disabled.
